### ISSUE TITLE
32 bit support

### ISSUE THREAD

**Issue by query-wow** [OutSystems/WebView#252]
Morning, trying to compile this to 32 bit but the app crashes. Does CEF glue have 32 bit support? 
Works fine for 64bit
```
Application: Program.exe
CoreCLR Version: 5.0.1522.11506
.NET Version: 5.0.15
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'libcef' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at Xilium.CefGlue.Interop.libcef.api_hash(Int32 entry)
   at Xilium.CefGlue.CefRuntime.CheckVersionByApiHash()
   at Xilium.CefGlue.CefRuntime.CheckVersion()
   at Xilium.CefGlue.CefRuntime.Load(String path)
   at Xilium.CefGlue.Common.CefRuntimeLoader.InternalInitialize(CefSettings settings, KeyValuePair`2[] flags, CustomScheme[] customSchemes, BrowserProcessHandler browserProcessHandler)
   at Xilium.CefGlue.Common.CefRuntimeLoader.<>c__DisplayClass2_0.<Initialize>b__0(BrowserProcessHandler browserProcessHandler)
   at Xilium.CefGlue.Common.CefRuntimeLoader.Load(BrowserProcessHandler browserProcessHandler)
   at Xilium.CefGlue.Common.BaseCefBrowser..ctor()
   at Xilium.CefGlue.Avalonia.AvaloniaCefBrowser..ctor()
   at WebViewControl.ChromiumBrowser..ctor()
   at WebViewControl.WebView.Initialize()
   at WebViewControl.WebView..ctor(Boolean useSharedDomain)
   at WebViewControl.WebView..ctor()
   at SyncTool.MainWindow.!XamlIlPopulate(IServiceProvider , MainWindow ) in Browser.MainWindow.xaml:line 354
   at SyncTool.MainWindow.!XamlIlPopulateTrampoline(MainWindow )
   at SyncTool.MainWindow..ctor() in E:\_Git\Browser\Browser\MainWindow.xaml.cs:line 63
   at SyncTool.App.OnFrameworkInitializationCompleted() in E:\_Git\Browser\Browser\App.xaml.cs:line 41
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 312
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at SyncTool.Program.Main(String[] args) in E:\_Git\Browser\Browser\Program.cs:line 8
   ```

**Comment by joaompneves** [comment]
Hi. CefGlue can support 32 bits but it would need some changes to include the [cef redist x86](https://www.nuget.org/packages/cef.redist.x86/) instead of the x64 version.

**Comment by query-wow** [comment]
Thanks for the reply, i'm gonna check how i can achieve this has i have to support a 32bit version.
