### ISSUE TITLE
 GPU process isn't usable. Goodbye.

### ISSUE THREAD

**Issue by JaneConan** [OutSystems/WebView#376]
![image](https://github.com/user-attachments/assets/f0e84a71-d941-4506-b19f-f6fdfa224bad)

The application to execute does not exist: '/home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/Xilium.CefGlue.BrowserProcess.dll'.
[1227/144946.521950:ERROR:gpu_process_host.cc(992)] GPU process exited unexpectedly: exit_code=39424
[1227/144946.522012:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 1 time(s)
The application to execute does not exist: '/home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/Xilium.CefGlue.BrowserProcess.dll'.
[1227/144946.527172:ERROR:gpu_process_host.cc(992)] GPU process exited unexpectedly: exit_code=39424
[1227/144946.527200:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 2 time(s)
The application to execute does not exist: '/home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/Xilium.CefGlue.BrowserProcess.dll'.
[1227/144946.532835:ERROR:gpu_process_host.cc(992)] GPU process exited unexpectedly: exit_code=39424
[1227/144946.532872:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 3 time(s)
The application to execute does not exist: '/home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/Xilium.CefGlue.BrowserProcess.dll'.
[1227/144946.538102:ERROR:gpu_process_host.cc(992)] GPU process exited unexpectedly: exit_code=39424
[1227/144946.538127:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 4 time(s)
The application to execute does not exist: '/home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/Xilium.CefGlue.BrowserProcess.dll'.
[1227/144946.543543:ERROR:gpu_process_host.cc(992)] GPU process exited unexpectedly: exit_code=39424
[1227/144946.543575:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 5 time(s)
The application to execute does not exist: '/home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/Xilium.CefGlue.BrowserProcess.dll'.
[1227/144946.549037:ERROR:gpu_process_host.cc(992)] GPU process exited unexpectedly: exit_code=39424
[1227/144946.549069:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 6 time(s)
The application to execute does not exist: '/home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/Xilium.CefGlue.BrowserProcess.dll'.
[1227/144946.554583:ERROR:gpu_process_host.cc(992)] GPU process exited unexpectedly: exit_code=39424
[1227/144946.554614:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 7 time(s)
The application to execute does not exist: '/home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/Xilium.CefGlue.BrowserProcess.dll'.
[1227/144946.559976:ERROR:gpu_process_host.cc(992)] GPU process exited unexpectedly: exit_code=39424
[1227/144946.560006:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 8 time(s)
The application to execute does not exist: '/home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/Xilium.CefGlue.BrowserProcess.dll'.
[1227/144946.565846:ERROR:gpu_process_host.cc(992)] GPU process exited unexpectedly: exit_code=39424
[1227/144946.565873:WARNING:gpu_process_host.cc(1362)] The GPU process has crashed 9 time(s)
[1227/144946.565899:FATAL:gpu_data_manager_impl_private.cc(448)] GPU process isn't usable. Goodbye.
[root@96d6cd927a0546c9bab4e37164469366 CefGlue.Demo.Avalonia]#

**Comment by Asces** [comment]
给 linux-x64/CefGlueBrowserProcess/Xilium.CefGlue.BrowserProcess 添加可执行权限。

**Comment by JaneConan** [comment]
[root@96d6cd927a0546c9bab4e37164469366 net8.0]# ./Xilium.CefGlue.Demo.Avalonia 
Unhandled exception. System.NotSupportedException: Can't find CEF in "/home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/"
 ---> System.DllNotFoundException: Unable to load shared library 'libcef' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/runtimes/linux-arm64/native/libcef.so: cannot open shared object file: No such file or directory
/root/dotnet/shared/Microsoft.NETCore.App/8.0.11/libcef.so: cannot open shared object file: No such file or directory
/home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/libcef.so: cannot open shared object file: No such file or directory
/home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/runtimes/linux-arm64/native/liblibcef.so: cannot open shared object file: No such file or directory
/root/dotnet/shared/Microsoft.NETCore.App/8.0.11/liblibcef.so: cannot open shared object file: No such file or directory
/home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/liblibcef.so: cannot open shared object file: No such file or directory
/home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/runtimes/linux-arm64/native/libcef: cannot open shared object file: No such file or directory
/root/dotnet/shared/Microsoft.NETCore.App/8.0.11/libcef: cannot open shared object file: No such file or directory
/home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/libcef: cannot open shared object file: No such file or directory
/home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/runtimes/linux-arm64/native/liblibcef: cannot open shared object file: No such file or directory
/root/dotnet/shared/Microsoft.NETCore.App/8.0.11/liblibcef: cannot open shared object file: No such file or directory
/home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/bin/Debug/net8.0/liblibcef: cannot open shared object file: No such file or directory

   at Xilium.CefGlue.Interop.libcef.api_hash(Int32 entry)
   at Xilium.CefGlue.CefRuntime.CheckVersionByApiHash() in /home/developer/下载/CefGlue/CefGlue/CefRuntime.cs:line 131
   --- End of inner exception stack trace ---
   at Xilium.CefGlue.CefRuntime.CheckVersionByApiHash() in /home/developer/下载/CefGlue/CefGlue/CefRuntime.cs:line 140
   at Xilium.CefGlue.CefRuntime.CheckVersion() in /home/developer/下载/CefGlue/CefGlue/CefRuntime.cs:line 109
   at Xilium.CefGlue.CefRuntime.Load(String path) in /home/developer/下载/CefGlue/CefGlue/CefRuntime.cs:line 83
   at Xilium.CefGlue.CefRuntime.Load() in /home/developer/下载/CefGlue/CefGlue/CefRuntime.cs:line 62
   at Xilium.CefGlue.Common.CefRuntimeLoader.InternalInitialize(CefSettings settings, KeyValuePair`2[] flags, CustomScheme[] customSchemes, BrowserProcessHandler browserProcessHandler) in /home/developer/下载/CefGlue/CefGlue.Common/CefRuntimeLoader.cs:line 25
   at Xilium.CefGlue.Common.CefRuntimeLoader.<>c__DisplayClass2_0.<Initialize>b__0(BrowserProcessHandler browserProcessHandler) in /home/developer/下载/CefGlue/CefGlue.Common/CefRuntimeLoader.cs:line 20
   at Xilium.CefGlue.Common.CefRuntimeLoader.Load(BrowserProcessHandler browserProcessHandler) in /home/developer/下载/CefGlue/CefGlue.Common/CefRuntimeLoader.cs:line 118
   at Xilium.CefGlue.Common.BaseCefBrowser..ctor(Func`1 cefRequestContextFactory) in /home/developer/下载/CefGlue/CefGlue.Common/BaseCefBrowser.cs:line 25
   at Xilium.CefGlue.Avalonia.AvaloniaCefBrowser..ctor(Func`1 cefRequestContextFactory) in /home/developer/下载/CefGlue/CefGlue.Avalonia/AvaloniaCefBrowser.cs:line 22
   at Xilium.CefGlue.Demo.Avalonia.BrowserView..ctor() in /home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/BrowserView.axaml.cs:line 27
   at Xilium.CefGlue.Demo.Avalonia.MainWindow.CreateNewTab() in /home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/MainWindow.axaml.cs:line 45
   at Xilium.CefGlue.Demo.Avalonia.MainWindow.InitializeComponent() in /home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/MainWindow.axaml.cs:line 25
   at Xilium.CefGlue.Demo.Avalonia.MainWindow..ctor() in /home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/MainWindow.axaml.cs:line 14
   at Xilium.CefGlue.Demo.Avalonia.App.OnFrameworkInitializationCompleted() in /home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/App.axaml.cs:line 18
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at Xilium.CefGlue.Demo.Avalonia.Program.Main(String[] args) in /home/developer/下载/CefGlue/CefGlue.Demo.Avalonia/Program.cs:line 20
Aborted（核心已转储）
[root@96d6cd927a0546c9bab4e37164469366 net8.0]# 



> 给 linux-x64/CefGlueBrowserProcess/Xilium.CefGlue.BrowserProcess 添加可执行权限。

有权限的
![微信截图_20250109153821](https://github.com/user-attachments/assets/ec510209-73ca-4a36-b20d-10b7f31e213b)

**Comment by Geektoolkit** [comment]
I hit this on Debian bookworm on a raspberry pi today. Looks like there is a duplicate issue filed 2 weeks ago as well
